# Skywars Tournament Config
debug: true
settings:
  concurrent-matches: 2
  max-players: 144
  group-size: 12
  chest-items:
    min: 4
    max: 8
loot:
  island:
    - STONE_SWORD:1:90
    - WOOD_SWORD:1:50
    - IRON_SWORD:1:10
    - LEATHER_HELMET:1:70
    - LEATHER_CHESTPLATE:1:70
    - LEATHER_LEGGINGS:1:70
    - LEATHER_BOOTS:1:70
    - GOLD_LEGGINGS:1:30
    - IRON_BOOTS:1:20
    - SNOW_BALL:16:100
    - EGG:12:50
    - LOG:16:100
    - WOOD:32:80
    - STONE:32:40
    - STONE_PICKAXE:1:50
    - STONE_AXE:1:50
    - COOKED_BEEF:8:100
    - APPLE:3:50
  semi-mid:
    - IRON_SWORD:1:100
    - DIAMOND_SWORD:1:15
    - BOW:1:80
    - ARROW:16:80
    - FISHING_ROD:1:60
    - IRON_HELMET:1:60
    - IRON_CHESTPLATE:1:40
    - IRON_LEGGINGS:1:50
    - IRON_BOOTS:1:60
    - CHAINMAIL_CHESTPLATE:1:50
    - GOLDEN_APPLE:1:50
    - TNT:5:60
    - FLINT_AND_STEEL:1:40
    - WATER_BUCKET:1:40
    - LAVA_BUCKET:1:40
  center:
    - DIAMOND_SWORD:1:100
    - DIAMOND_CHESTPLATE:1:60
    - DIAMOND_LEGGINGS:1:60
    - DIAMOND_HELMET:1:60
    - DIAMOND_BOOTS:1:60
    - ENDER_PEARL:3:90
    - GOLDEN_APPLE:3:80
    - BOW:1:50
    - ARROW:32:50
    - EXP_BOTTLE:16:40
arenas:
  Prelude:
    spawns:
      - Prelude,-31.46263957464033,61.0,43.390736337850136,180.29517,0.7500992
      - Prelude,-45.568511963470655,61.0,29.491391112478144,270.89417,1.0500973
      - Prelude,-45.479203657278475,61.0,10.534015515404636,269.84082,-1.0498439
      - Prelude,-45.587575711373894,61.0,-9.391865316952202,269.99158,-0.29992628
      - Prelude,-45.466743877030616,61.0,-28.440533703079485,270.1394,-0.9000055
      - Prelude,-31.541674851896236,61.0,-41.528787252377946,359.98938,-1.3500327
      - Prelude,32.43268504273893,61.0,-41.485431471492426,0.43920898,-0.45001727
      - Prelude,46.446774558502426,61.0,-28.48837036158462,91.03845,-1.6498915
      - Prelude,46.68066870284752,61.0,-9.510981185010545,90.58899,0.30015057
      - Prelude,46.55998260771626,61.0,10.539289078009533,90.28955,0.6001157
      - Prelude,46.49706518689332,61.0,29.554894620073654,89.988525,-0.749934
      - Prelude,32.58044660156031,61.0,42.423276595085724,179.83728,-2.5499303
    pos1: Prelude,80.5,100.15274362253479,76.5,144.15135,25.950224
    pos2: Prelude,-79.5,-40.0,-75.5,255.30125,-73.950005
